<?php if($dates = $this->getDeliveryDateArrayOptions()): ?>
    <li>
        <label for="shipping-deliverydate"><?php echo $this->__('Desired Delivery Date') ?></label>
        <div class="input-box">
            <select id="shipping-deliverydate" name="komplizierte_delivery_date" title="<?php echo $this->__('Desired Delivery Date') ?>">
                <?php
                $this->getDeliveryDateArrayOptions();
                foreach($dates as $date => $label):
                    ?>
                    <option value="<?php echo $date; ?>" <?php if($date == $this->getSelectedDeliveryDate()) echo ' selected="selected"';?>><?php echo $label; ?></option>
                <?php
                endforeach;
                ?>
            </select>
        </div>
    </li>
<?php endif ?>